import MainHeader from "@/app/_components/Layouts/Header";
import "@/app/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ params, children }) {
  return (
    <>
      <title>impretion</title>
      <MainHeader />
      <section>{children}</section>
    </>
  );
}
